services:
  signer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: signer-service-prod
    #command: npx nodemon --exec ts-node server.ts
    command: node dist/server.js
    #Не забыть закоментировать
    volumes:
      - ./:/var/www/signer
      - /var/www/signer/node_modules
    env_file: .env
    ports:
      - "3001:3000"
    networks:
      - signer
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: signer-redis
    volumes:
    - redis-data:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - signer
volumes:
  redis-data:

networks:
  signer:
